version: "3"
services:
  postgres:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - app-network
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - app-network

  web:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/inception
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - app-network

  celery:
    build: .
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    external: true
volumes:
  postgres_data: