version: "3"
services:
    rabbitmq:
        image: "bitnami/rabbitmq"
        restart: always        
        ports:
          - "4369:4369"
          - "5672:5672"
          - "25672:25672"
          - "15672:15672"
        volumes:
          - "rabbitmq_data:/bitnami"
        environment:
          - RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT=1000000000
        networks:
          - app-network
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:15672"]
            interval: 30s
            timeout: 10s
            retries: 5
    
    redis:
        image: "bitnami/redis:5.0.4"
        restart: always
        environment:
          - REDIS_PASSWORD=password123
        ports:
          - "6379:6379"
        volumes:
          - "redis_data:/bitnami/redis/data"
        networks:
          - app-network
networks: 
      app-network:
        external: true
volumes:
    rabbitmq_data:
        driver: local
    redis_data:
        driver: local